---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ap-southeast-2
  version: "1.21"

availabilityZones: ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t2.micro
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:ap-southeast-2:117134819170:key/44b198e2-4932-4210-8ed9-9d77f2c79a47
